GET https://127.0.0.1/api/user HTTP/1.1

###

POST https://127.0.0.1/api/user/signup HTTP/1.1
content-type: application/json

{
    "id" : "buyer_id",
    "email" : "buyer@gmail.com",
    "password": "12!1234qwer",
    "phone" : "0298336521",
    "profile_picture" : "/picture/test21.jpg",
    "location_id" : "test_location_id",
    "role" : "admin"
}

###

POST https://127.0.0.1/api/user/logout HTTP/1.1

###

POST https://127.0.0.1/api/user/signin HTTP/1.1
content-type: application/json

{
    "email" : "newseller@gmail.com",
    "password": "12!1234qwer"
}

###

GET https://127.0.0.1/api/listing HTTP/1.1

###

POST https://127.0.0.1/api/listing HTTP/1.1
content-type: application/json

{
    "name" : "test listing",
    "description" : "test description",
    "price" : 1000.0,
    "location_id" : null,
    "userId" : "seller_id",
    "category_id" : null,
    "isAvailable" :true,
    "pictures": ["/pic1.jpg", "/pic2.jpg", "/pic3.jpg"]
}

###

POST https://127.0.0.1/api/user/password-reset HTTP/1.1
content-type: application/json

{
    "email" : "slepoipios@gmail.com"
}

###

POST https://127.0.0.1/api/user/password-reset/test_id/4b3507dac3fff51993d0aef083e300f104ea1b2163f723a090da026927086584 HTTP/1.1
content-type: application/json

{
    "password": "new_password"
}

###

POST https://127.0.0.1/api/chat HTTP/1.1
content-type: application/json

{
    "listingId":"seller_listing_id"
}

###

POST https://127.0.0.1/api/message HTTP/1.1
content-type: application/json

{
    "chatId" : "385873aa-0e23-4fe2-8b4b-4773e7cb7b9b",
    "text" : "2 seller message"
}

###

GET https://127.0.0.1/api/message/385873aa-0e23-4fe2-8b4b-4773e7cb7b9b HTTP/1.1

###

GET https://127.0.0.1/api/chat/385873aa-0e23-4fe2-8b4b-4773e7cb7b9b HTTP/1.1

###

GET https://127.0.0.1/api/user/buyer_id HTTP/1.1

###

PUT https://127.0.0.1/api/user/seller_id HTTP/1.1
content-type: application/json

{
    "email": "newseller@gmail.com",
    "phone": "0298336522",
    "profile_picture": "/picture/new_picture.jpg",
    "location_id": "new_location_id"
}

###

DELETE https://127.0.0.1/api/user/buyer_id HTTP/1.1

###

GET https://127.0.0.1/api/listing HTTP/1.1

###

GET https://127.0.0.1/api/image HTTP/1.1

###
POST https://127.0.0.1/api/image HTTP/1.1
Content-Type: application/json

{
    "id": "image_id",
    "url": "/path/to/image.jpg",
    "listingId": null,
    "userId": null
}

###
POST https://127.0.0.1/api/image HTTP/1.1
Content-Type: application/json

{
    "id": "image_id1",
    "url": "/path/to/image1.jpg",
    "listingId": null,
    "userId": "seller_id"
}

###

GET https://127.0.0.1/api/image HTTP/1.1

###

GET https://127.0.0.1/api/image/image_id HTTP/1.1

###

GET https://127.0.0.1/api/location HTTP/1.1

###

POST https://127.0.0.1/api/location HTTP/1.1
Content-Type: application/json

{
    "id": "location_id",
    "name": "New York"
}

###

POST https://127.0.0.1/api/location HTTP/1.1
Content-Type: application/json

{
    "id": "location_id1",
    "name": "Odesa"
}

###

GET https://127.0.0.1/api/location/location_id HTTP/1.1

###

GET https://127.0.0.1/api/category HTTP/1.1

###

POST https://127.0.0.1/api/category HTTP/1.1
Content-Type: application/json

{
    "id": "electronics",
    "name": "Electronics",
    "parentId": null
}

###

POST https://127.0.0.1/api/category HTTP/1.1
Content-Type: application/json

{
    "id": "smartphones",
    "name": "Сматртфони",
    "parentId": "electronics"
}

###

DELETE https://127.0.0.1/api/category/category_id HTTP/1.1
